In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import librosa
import librosa.display
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from matplotlib.pyplot import specgram
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
import seaborn as sns
import keras
from keras.callbacks import ReduceLROnPlateau
from keras.models import Sequential
from keras.layers import Dense, Conv1D, LSTM, MaxPooling1D, Flatten, Dropout, BatchNormalization
from keras.utils import to_categorical
from keras.callbacks import ModelCheckpoint
from keras import regularizers
import os
import glob
import pandas as pd
import IPython.display as ipd
import plotly.express as px
import scipy.io.wavfile
import sys
import warnings
if not sys.warnoptions:
    warnings.simplefilter("ignore")
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [ ]:
#Xuất dữ liệu
RAV = '/content/drive/MyDrive/Colab Notebooks/DATA/RAVDESS/audio_speech_actors_01-24/'
dir_list = os.listdir(RAV)

emotion = [] #biểu thị cảm xúc của âm thanh
gender = [] #giới tính của người nói
path = [] #đường dẫn đến file âm thanh tương ứng
feature = []
#Phân tích tên file âm thanh để trích xuất thông tin về cảm xúc và giới tính của người nói.
for i in dir_list:
    fname = os.listdir(RAV + i)
    for f in fname:
        part = f.split('.')[0].split('-')
        emotion.append(int(part[2]))
        temp = int(part[6])
        if temp%2 == 0:
            temp = "female"
        else:
            temp = "male"
        gender.append(temp)
        path.append(RAV + i + '/' + f)

#Xây dựng DataFrame RAV_df từ các thông tin đã trích xuất
RAV_df = pd.DataFrame(emotion)
RAV_df = RAV_df.replace({1:'neutral', 2:'calm', 3:'happy', 4:'sad', 5:'angry', 6:'fear', 7:'disgust', 8:'surprise'})
RAV_df = pd.concat([pd.DataFrame(gender),RAV_df],axis=1)
RAV_df.columns = ['gender','emotion']
RAV_df['labels'] =RAV_df.gender + '_' + RAV_df.emotion
RAV_df['source'] = 'RAVDESS'
RAV_df = pd.concat([RAV_df,pd.DataFrame(path, columns = ['path'])],axis=1)
#Loại bỏ cột 'gender' và hiển thị số lượng mẫu dữ liệu cho mỗi nhãn cảm xúc.
RAV_df = RAV_df.drop(['gender'], axis=1)
RAV_df.labels.value_counts()

labels
male_calm          96
male_happy         96
male_fear          96
male_disgust       96
male_sad           96
male_angry         96
male_surprise      96
female_calm        96
female_surprise    96
female_happy       96
female_fear        96
female_disgust     96
female_sad         96
female_angry       96
male_neutral       48
female_neutral     48
Name: count, dtype: int64

In [ ]:
# Hàm làm nhiễu âm thanh
def noise(data):
    noise_amp = 0.035*np.random.uniform()*np.amax(data)
    data = data + noise_amp*np.random.normal(size=data.shape[0])
    return data

# Hàm kéo dài âm thanh
def stretch(data, rate=0.8):
    return librosa.effects.time_stretch(data, rate = rate)

# Hàm nhấn mạnh/thấp âm thanh
def pitch(data, sampling_rate, pitch_factor=0.7):
   # return librosa.effects.pitch_shift(data, sampling_rate, pitch_factor)
    return librosa.effects.pitch_shift(y=data, sr=sampling_rate, n_steps=pitch_factor)

path = np.array(RAV_df.path)[1]
data, sample_rate = librosa.load(path)

In [ ]:
# Hàm trích xuất các đặc trưng từ dữ liệu
def extract_features(data):
    # ZCR: Tần số băng qua không là tốc độ tín hiệu thay đổi từ dương sang 0 sang âm hoặc từ âm sang 0 sang dương
    result = np.array([])
    zcr = np.mean(librosa.feature.zero_crossing_rate(y=data).T, axis=0)
    result=np.hstack((result, zcr))

    # Chroma_stft : Thể hiện phân bố tần số của các nốt nhạc trong tín hiệu âm thanh.
    stft = np.abs(librosa.stft(data))
    chroma_stft = np.mean(librosa.feature.chroma_stft(S=stft, sr=sample_rate).T, axis=0)
    result = np.hstack((result, chroma_stft))

    # MFCC : Là một bộ các đặc trưng được sử dụng phổ biến trong xử lý tín hiệu âm thanh
    mfcc = np.mean(librosa.feature.mfcc(y=data, sr=sample_rate).T, axis=0)
    result = np.hstack((result, mfcc))

    # Root Mean Square Value: Là một đại lượng thể hiện sức mạnh trung bình của tín hiệu âm thanh trong mỗi cửa sổ thời gian
    rms = np.mean(librosa.feature.rms(y=data).T, axis=0)
    result = np.hstack((result, rms))

    # MelSpectogram : là biểu diễn trực quan của phổ tần số của tín hiệu âm thanh,
    #trong đó các tần số được biểu diễn trên trục y dưới dạng các băng thông mel thay vì Hz.
    mel = np.mean(librosa.feature.melspectrogram(y=data, sr=sample_rate).T, axis=0)
    result = np.hstack((result, mel))

    return result
# Hàm trích xuất các đặc trưng từ dữ liệu âm-thanh
def get_features(path):
    # Xử lý thời lượng và độ lệch được sử dụng để xử lý phần không có âm thanh khi bắt đầu và kết thúc của mỗi tệp âm thanh
    data, sample_rate = librosa.load(path, duration=2.5, offset=0.6)

    # Với không tăng cường
    res1 = extract_features(data)
    result = np.array(res1)

    # làm nhiễu dữ liệu
    noise_data = noise(data)
    res2 = extract_features(noise_data)
    result = np.vstack((result, res2))

    # kéo dãn và nhấn mạnh/thấp của âm thanh
    new_data = stretch(data)
    data_stretch_pitch = pitch(new_data, sample_rate)
    res3 = extract_features(data_stretch_pitch)
    result = np.vstack((result, res3))

    return result

In [ ]:
# Thêm cảm xúc 3 lần vì đã thực hiện 3 kỹ thuật
# tăng cường trên mỗi tệp âm thanh
X, Y = [], []
for path, emotion in zip(RAV_df.path, RAV_df.emotion):
    feature = get_features(path)
    for ele in feature:
        X.append(ele)
        Y.append(emotion)

In [ ]:
#mã trả về kích thước của X, Y và số lượng đường dẫn âm thanh trong RAV_df
len(X), len(Y), RAV_df.path.shape

(4320, 4320, (1440,))

In [ ]:
Features = pd.DataFrame(X)
Features['labels'] = Y
Features.to_csv('features.csv', index=False)

In [ ]:
#Hiển thị một số dòng đầu tiên và thống kê
display(Features.head())
display(Features.describe())

,0,1,2,3,4,5,6,7,8,9,...,153,154,155,156,157,158,159,160,161,labels
0,0.178354,0.810467,0.707073,0.600536,0.604771,0.648013,0.626874,0.597224,0.663339,0.611452,...,0.000007,0.000007,0.000005,0.000006,4.284741e-06,3.988983e-06,2.407329e-06,8.899194e-07,5.797154e-08,calm
1,0.244113,0.833011,0.769919,0.685230,0.672871,0.730226,0.707466,0.643585,0.701534,0.667796,...,0.000010,0.000010,0.000009,0.000009,7.154689e-06,7.024819e-06,5.463309e-06,4.067468e-06,3.150575e-06,calm
2,0.155165,0.798484,0.703550,0.579219,0.577016,0.626991,0.629416,0.593090,0.621296,0.578494,...,0.000001,0.000001,0.000002,0.000001,1.141171e-06,1.048393e-06,8.726456e-07,4.501752e-07,2.529665e-08,calm
3,0.190448,0.694625,0.730583,0.733133,0.739128,0.721110,0.699378,0.653086,0.710711,0.744858,...,0.000003,0.000003,0.000002,0.000001,8.644034e-07,6.660677e-07,4.428955e-07,2.127365e-07,1.714209e-08,calm
4,0.298362,0.762934,0.813067,0.825032,0.807019,0.816541,0.797787,0.705642,0.719028,0.785051,...,0.000006,0.000006,0.000006,0.000005,4.351570e-06,4.316964e-06,3.867805e-06,3.606170e-06,3.340686e-06,calm

,0,1,2,3,4,5,6,7,8,9,...,152,153,154,155,156,157,158,159,160,161
count,4320.000000,4320.000000,4320.000000,4320.000000,4320.000000,4320.000000,4320.000000,4320.000000,4320.000000,4320.000000,...,4.320000e+03,4.320000e+03,4.320000e+03,4.320000e+03,4.320000e+03,4.320000e+03,4.320000e+03,4.320000e+03,4.320000e+03,4.320000e+03
mean,0.211121,0.628428,0.631577,0.636531,0.646507,0.635523,0.606690,0.601078,0.620231,0.637284,...,1.779771e-03,1.793143e-03,1.831893e-03,1.864603e-03,1.916061e-03,1.950074e-03,1.949950e-03,1.905177e-03,1.411315e-03,7.784153e-04
std,0.069117,0.088274,0.097486,0.100497,0.102293,0.104690,0.091320,0.078644,0.080453,0.079320,...,6.240931e-03,6.355623e-03,6.476028e-03,6.611748e-03,6.862573e-03,6.875121e-03,6.793565e-03,6.474040e-03,5.460085e-03,4.387025e-03
min,0.060091,0.339261,0.287322,0.274451,0.261138,0.263614,0.269487,0.262952,0.242573,0.269642,...,2.135466e-08,1.692912e-08,2.129327e-08,2.400430e-08,2.899627e-08,2.325185e-08,6.041326e-08,7.742912e-08,3.497832e-08,2.159462e-09
25%,0.154699,0.569826,0.566439,0.566941,0.576088,0.565761,0.550482,0.554671,0.569795,0.585708,...,2.889440e-05,2.915450e-05,3.025457e-05,3.169591e-05,3.468735e-05,3.388159e-05,3.454783e-05,3.352481e-05,2.002263e-05,2.042758e-06
50%,0.202447,0.632453,0.637594,0.642649,0.653017,0.643769,0.616098,0.609397,0.626726,0.644084,...,1.689116e-04,1.695381e-04,1.719652e-04,1.836441e-04,1.873425e-04,1.839164e-04,1.890032e-04,1.839554e-04,1.161665e-04,1.467828e-05
75%,0.268904,0.692666,0.701654,0.709678,0.722579,0.709448,0.670835,0.655954,0.678216,0.692803,...,8.872470e-04,8.834441e-04,9.528763e-04,9.190238e-04,9.475904e-04,9.537891e-04,9.481863e-04,9.470188e-04,6.167429e-04,1.152594e-04
max,0.406639,0.875499,0.879135,0.901239,0.907017,0.903683,0.880184,0.813967,0.825856,0.868189,...,1.053029e-01,1.098827e-01,1.089929e-01,9.879018e-02,1.142716e-01,1.079606e-01,1.240226e-01,1.042664e-01,9.820467e-02,8.280677e-02

In [ ]:
# Xác định dữ liệu đầu vào và đầu ra
X = Features.iloc[:, :-1].values  # Ma trận đặc trưng
Y = Features['labels'].values     # Vector nhãn

# Mã hóa nhãn sang dạng one-hot
encoder = OneHotEncoder()
Y_encoded = encoder.fit_transform(np.array(Y).reshape(-1,1)).toarray()

# Phân chia dữ liệu thành tập huấn luyện và tập kiểm tra
x_train, x_test, y_train, y_test = train_test_split(X, Y_encoded, random_state=0, shuffle=True)

# Chuẩn hóa dữ liệu
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

# Mở rộng số chiều của dữ liệu
x_train_reshaped = np.expand_dims(x_train_scaled, axis=2)  # Tập huấn luyện
x_test_reshaped = np.expand_dims(x_test_scaled, axis=2)    # Tập kiểm tra

In [ ]:
# Mô hình LSTM
model_lstm = Sequential()

model_lstm.add(Conv1D(128, kernel_size=3, strides=1, padding='same', activation='relu'))
model_lstm.add(BatchNormalization())
model_lstm.add(MaxPooling1D(pool_size=3, strides=2, padding='same'))

model_lstm.add(Conv1D(64, kernel_size=3, strides=1, padding='same', activation='relu'))
model_lstm.add(BatchNormalization())
model_lstm.add(MaxPooling1D(pool_size=3, strides=2, padding='same'))

model_lstm.add(Conv1D(32, kernel_size=3, strides=1, padding='same', activation='relu'))
model_lstm.add(BatchNormalization())
model_lstm.add(MaxPooling1D(pool_size=3, strides=2, padding='same'))

model_lstm.add(Flatten())
model_lstm.add(Dense(128, activation='relu'))
model_lstm.add(BatchNormalization())
model_lstm.add(Dropout(0.2))

model_lstm.add(Dense(64, activation='relu'))
model_lstm.add(Dense(32, activation='relu'))

model_lstm.add(Dense(8, activation='softmax'))
model_lstm.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

model_lstm.build(input_shape=(None, x_train_reshaped.shape[1], 1))
model_lstm.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_8 (Conv1D)               │ (None, 162, 128)       │           512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_5           │ (None, 162, 128)       │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_8 (MaxPooling1D)  │ (None, 81, 128)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_9 (Conv1D)               │ (None, 81, 64)         │        24,640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_6           │ (None, 81, 64)         │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_9 (MaxPooling1D)  │ (None, 41, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_10 (Conv1D)              │ (None, 41, 32)         │         6,176 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_7           │ (None, 41, 32)         │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_10 (MaxPooling1D) │ (None, 21, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ (None, 672)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 128)            │        86,144 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_8           │ (None, 128)            │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_8 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 8)              │           264 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 129,480 (505.78 KB)

 Trainable params: 128,776 (503.03 KB)

 Non-trainable params: 704 (2.75 KB)

In [ ]:
# Mô hình CNN
model_cnn = Sequential()
model_cnn.add(Conv1D(256, kernel_size=5, strides=1, padding='same', activation='relu', input_shape=(x_train.shape[1], 1)))
model_cnn.add(MaxPooling1D(pool_size=5, strides = 2, padding = 'same'))

model_cnn.add(Conv1D(128, kernel_size=5, strides=1, padding='same', activation='relu'))
model_cnn.add(MaxPooling1D(pool_size=5, strides = 2, padding = 'same'))

model_cnn.add(Conv1D(64, kernel_size=5, strides=1, padding='same', activation='relu'))
model_cnn.add(MaxPooling1D(pool_size=5, strides = 2, padding = 'same'))
model_cnn.add(Dropout(0.2))

model_cnn.add(Conv1D(32, kernel_size=5, strides=1, padding='same', activation='relu'))
model_cnn.add(MaxPooling1D(pool_size=5, strides = 2, padding = 'same'))

model_cnn.add(Flatten())
model_cnn.add(Dense(units=16, activation='relu'))
model_cnn.add(Dropout(0.3))

model_cnn.add(Dense(units=8, activation='softmax'))
model_cnn.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

model_cnn.build(input_shape=(None, x_train.shape[1], 1))
model_cnn.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_2 (Conv1D)               │ (None, 162, 256)       │         1,536 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_2 (MaxPooling1D)  │ (None, 81, 256)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_3 (Conv1D)               │ (None, 81, 128)        │       163,968 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_3 (MaxPooling1D)  │ (None, 41, 128)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_4 (Conv1D)               │ (None, 41, 64)         │        41,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_4 (MaxPooling1D)  │ (None, 21, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 21, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_5 (Conv1D)               │ (None, 21, 32)         │        10,272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_5 (MaxPooling1D)  │ (None, 11, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 352)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 16)             │         5,648 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 8)              │           136 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 222,584 (869.47 KB)

 Trainable params: 222,584 (869.47 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
y_pred_lstm = np.argmax(model_lstm.predict(x_test_reshaped), axis=1)
y_pred_cnn = np.argmax(model_cnn.predict(x_test_reshaped), axis=1)
y_test_labels = np.argmax(y_test, axis=1)

34/34 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step
34/34 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step

In [ ]:
from sklearn.utils.class_weight import compute_class_weight

classes = np.unique(np.argmax(y_train, axis=1))
class_weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=np.argmax(y_train, axis=1)
)
class_weight_dict = dict(enumerate(class_weights))
print("Class weights:", class_weight_dict)

Class weights: {0: np.float64(0.9246575342465754), 1: np.float64(0.9310344827586207), 2: np.float64(0.9331797235023042), 3: np.float64(0.9440559440559441), 4: np.float64(0.9735576923076923), 5: np.float64(1.9103773584905661), 6: np.float64(0.9353348729792148), 7: np.float64(0.9142212189616253)}

In [ ]:
from keras.callbacks import EarlyStopping, ModelCheckpoint

callbacks_lstm = [
    ReduceLROnPlateau(monitor='val_loss', factor=0.5,
                      patience=5, min_lr=1e-7, verbose=1),
    EarlyStopping(monitor='val_loss', patience=15,
                  restore_best_weights=True, verbose=1),
    ModelCheckpoint('best_lstm.keras', save_best_only=True,
                    monitor='val_loss', verbose=1)
]

history_lstm = model_lstm.fit(
    x_train_reshaped, y_train,
    batch_size=32,         # giảm batch size
    epochs=100,
    validation_data=(x_test_reshaped, y_test),
    class_weight=class_weight_dict,
    callbacks=callbacks_lstm
)

Epoch 1/100
102/102 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.2186 - loss: 2.0560
Epoch 1: val_loss improved from None to 2.06240, saving model to best_lstm.keras

Epoch 1: finished saving model to best_lstm.keras
102/102 ━━━━━━━━━━━━━━━━━━━━ 14s 60ms/step - accuracy: 0.2556 - loss: 1.9159 - val_accuracy: 0.1250 - val_loss: 2.0624 - learning_rate: 0.0010
Epoch 2/100
 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3590 - loss: 1.6975
Epoch 2: val_loss did not improve from 2.06240
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.3577 - loss: 1.6814 - val_accuracy: 0.1778 - val_loss: 2.2817 - learning_rate: 0.0010
Epoch 3/100
102/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4275 - loss: 1.5343
Epoch 3: val_loss did not improve from 2.06240
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.4281 - loss: 1.5297 - val_accuracy: 0.1491 - val_loss: 2.3079 - learning_rate: 0.0010
Epoch 4/100
 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4576 - loss: 1.4644
Epoch 4: val_loss did not improve from 2.06240
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.4562 - loss: 1.4515 - val_accuracy: 0.2833 - val_loss: 2.0644 - learning_rate: 0.0010
Epoch 5/100
 99/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4749 - loss: 1.3848
Epoch 5: val_loss improved from 2.06240 to 1.89313, saving model to best_lstm.keras

Epoch 5: finished saving model to best_lstm.keras
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4799 - loss: 1.3734 - val_accuracy: 0.3278 - val_loss: 1.8931 - learning_rate: 0.0010
Epoch 6/100
101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5347 - loss: 1.2704
Epoch 6: val_loss improved from 1.89313 to 1.51159, saving model to best_lstm.keras

Epoch 6: finished saving model to best_lstm.keras
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5185 - loss: 1.2998 - val_accuracy: 0.4093 - val_loss: 1.5116 - learning_rate: 0.0010
Epoch 7/100
102/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5256 - loss: 1.2438
Epoch 7: val_loss improved from 1.51159 to 1.49067, saving model to best_lstm.keras

Epoch 7: finished saving model to best_lstm.keras
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5423 - loss: 1.2180 - val_accuracy: 0.4704 - val_loss: 1.4907 - learning_rate: 0.0010
Epoch 8/100
 94/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5829 - loss: 1.1496
Epoch 8: val_loss improved from 1.49067 to 1.42273, saving model to best_lstm.keras

Epoch 8: finished saving model to best_lstm.keras
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5954 - loss: 1.1271 - val_accuracy: 0.4574 - val_loss: 1.4227 - learning_rate: 0.0010
Epoch 9/100
 94/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6134 - loss: 1.0155
Epoch 9: val_loss improved from 1.42273 to 1.38837, saving model to best_lstm.keras

Epoch 9: finished saving model to best_lstm.keras
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5994 - loss: 1.0533 - val_accuracy: 0.4954 - val_loss: 1.3884 - learning_rate: 0.0010
Epoch 10/100
 95/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6382 - loss: 0.9709
Epoch 10: val_loss did not improve from 1.38837
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.6198 - loss: 1.0112 - val_accuracy: 0.4528 - val_loss: 1.7088 - learning_rate: 0.0010
Epoch 11/100
100/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6750 - loss: 0.9021
Epoch 11: val_loss did not improve from 1.38837
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.6586 - loss: 0.9299 - val_accuracy: 0.3972 - val_loss: 1.9221 - learning_rate: 0.0010
Epoch 12/100
 95/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6717 - loss: 0.9015
Epoch 12: val_loss improved from 1.38837 to 1.32114, saving model to best_lstm.keras

Epoch 12: finished saving model to best_lstm.keras
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.6617 - loss: 0.9198 - val_accuracy: 0.5611 - val_loss: 1.3211 - learning_rate: 0.0010
Epoch 13/100
101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6981 - loss: 0.8155
Epoch 13: val_loss improved from 1.32114 to 1.20696, saving model to best_lstm.keras

Epoch 13: finished saving model to best_lstm.keras
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.6867 - loss: 0.8429 - val_accuracy: 0.5731 - val_loss: 1.2070 - learning_rate: 0.0010
Epoch 14/100
 97/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7022 - loss: 0.7906
Epoch 14: val_loss did not improve from 1.20696
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6926 - loss: 0.8149 - val_accuracy: 0.5704 - val_loss: 1.2908 - learning_rate: 0.0010
Epoch 15/100
 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7364 - loss: 0.7391
Epoch 15: val_loss did not improve from 1.20696
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7352 - loss: 0.7504 - val_accuracy: 0.5528 - val_loss: 1.3255 - learning_rate: 0.0010
Epoch 16/100
 93/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7434 - loss: 0.7102
Epoch 16: val_loss did not improve from 1.20696
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7432 - loss: 0.7020 - val_accuracy: 0.5500 - val_loss: 1.2894 - learning_rate: 0.0010
Epoch 17/100
 92/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7664 - loss: 0.6642
Epoch 17: val_loss did not improve from 1.20696
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7583 - loss: 0.6646 - val_accuracy: 0.5796 - val_loss: 1.3523 - learning_rate: 0.0010
Epoch 18/100
 93/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7869 - loss: 0.6000
Epoch 18: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.

Epoch 18: val_loss did not improve from 1.20696
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7781 - loss: 0.6106 - val_accuracy: 0.5241 - val_loss: 1.5220 - learning_rate: 0.0010
Epoch 19/100
 93/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7876 - loss: 0.5738
Epoch 19: val_loss improved from 1.20696 to 1.16794, saving model to best_lstm.keras

Epoch 19: finished saving model to best_lstm.keras
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8056 - loss: 0.5217 - val_accuracy: 0.6000 - val_loss: 1.1679 - learning_rate: 5.0000e-04
Epoch 20/100
 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8523 - loss: 0.4222
Epoch 20: val_loss improved from 1.16794 to 1.05810, saving model to best_lstm.keras

Epoch 20: finished saving model to best_lstm.keras
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8423 - loss: 0.4468 - val_accuracy: 0.6398 - val_loss: 1.0581 - learning_rate: 5.0000e-04
Epoch 21/100
 95/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8385 - loss: 0.4392
Epoch 21: val_loss did not improve from 1.05810
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8426 - loss: 0.4354 - val_accuracy: 0.6352 - val_loss: 1.0758 - learning_rate: 5.0000e-04
Epoch 22/100
 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8671 - loss: 0.3687
Epoch 22: val_loss did not improve from 1.05810
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8602 - loss: 0.3904 - val_accuracy: 0.6148 - val_loss: 1.2456 - learning_rate: 5.0000e-04
Epoch 23/100
 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8476 - loss: 0.4185
Epoch 23: val_loss did not improve from 1.05810
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8512 - loss: 0.4073 - val_accuracy: 0.6343 - val_loss: 1.1136 - learning_rate: 5.0000e-04
Epoch 24/100
 93/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8913 - loss: 0.3325
Epoch 24: val_loss did not improve from 1.05810
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8762 - loss: 0.3508 - val_accuracy: 0.6324 - val_loss: 1.1782 - learning_rate: 5.0000e-04
Epoch 25/100
 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8860 - loss: 0.3041
Epoch 25: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.

Epoch 25: val_loss did not improve from 1.05810
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8722 - loss: 0.3480 - val_accuracy: 0.6500 - val_loss: 1.1408 - learning_rate: 5.0000e-04
Epoch 26/100
 95/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8825 - loss: 0.3166
Epoch 26: val_loss improved from 1.05810 to 1.04496, saving model to best_lstm.keras

Epoch 26: finished saving model to best_lstm.keras
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8855 - loss: 0.3131 - val_accuracy: 0.6722 - val_loss: 1.0450 - learning_rate: 2.5000e-04
Epoch 27/100
 95/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9182 - loss: 0.2524
Epoch 27: val_loss did not improve from 1.04496
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9096 - loss: 0.2663 - val_accuracy: 0.6583 - val_loss: 1.0835 - learning_rate: 2.5000e-04
Epoch 28/100
 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9163 - loss: 0.2372
Epoch 28: val_loss did not improve from 1.04496
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9160 - loss: 0.2413 - val_accuracy: 0.6593 - val_loss: 1.1204 - learning_rate: 2.5000e-04
Epoch 29/100
 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9203 - loss: 0.2410
Epoch 29: val_loss did not improve from 1.04496
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9170 - loss: 0.2462 - val_accuracy: 0.6574 - val_loss: 1.0854 - learning_rate: 2.5000e-04
Epoch 30/100
 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9345 - loss: 0.2139
Epoch 30: val_loss did not improve from 1.04496
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9247 - loss: 0.2258 - val_accuracy: 0.6565 - val_loss: 1.0692 - learning_rate: 2.5000e-04
Epoch 31/100
 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9189 - loss: 0.2268
Epoch 31: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.

Epoch 31: val_loss did not improve from 1.04496
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9176 - loss: 0.2343 - val_accuracy: 0.6741 - val_loss: 1.1059 - learning_rate: 2.5000e-04
Epoch 32/100
 94/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9344 - loss: 0.2043
Epoch 32: val_loss did not improve from 1.04496
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9299 - loss: 0.2087 - val_accuracy: 0.6556 - val_loss: 1.0884 - learning_rate: 1.2500e-04
Epoch 33/100
 99/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9369 - loss: 0.1922
Epoch 33: val_loss did not improve from 1.04496
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9380 - loss: 0.1986 - val_accuracy: 0.6667 - val_loss: 1.0730 - learning_rate: 1.2500e-04
Epoch 34/100
 97/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9461 - loss: 0.1703
Epoch 34: val_loss did not improve from 1.04496
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9441 - loss: 0.1790 - val_accuracy: 0.6611 - val_loss: 1.0962 - learning_rate: 1.2500e-04
Epoch 35/100
 97/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9431 - loss: 0.1717
Epoch 35: val_loss did not improve from 1.04496
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9410 - loss: 0.1749 - val_accuracy: 0.6806 - val_loss: 1.0797 - learning_rate: 1.2500e-04
Epoch 36/100
 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9365 - loss: 0.1955
Epoch 36: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.

Epoch 36: val_loss did not improve from 1.04496
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9423 - loss: 0.1808 - val_accuracy: 0.6741 - val_loss: 1.0986 - learning_rate: 1.2500e-04
Epoch 37/100
100/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9485 - loss: 0.1662
Epoch 37: val_loss did not improve from 1.04496
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9451 - loss: 0.1679 - val_accuracy: 0.6722 - val_loss: 1.0876 - learning_rate: 6.2500e-05
Epoch 38/100
 92/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9558 - loss: 0.1413
Epoch 38: val_loss did not improve from 1.04496
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9537 - loss: 0.1517 - val_accuracy: 0.6657 - val_loss: 1.0995 - learning_rate: 6.2500e-05
Epoch 39/100
 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9483 - loss: 0.1470
Epoch 39: val_loss did not improve from 1.04496
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9481 - loss: 0.1501 - val_accuracy: 0.6694 - val_loss: 1.0962 - learning_rate: 6.2500e-05
Epoch 40/100
 93/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9466 - loss: 0.1633
Epoch 40: val_loss did not improve from 1.04496
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9497 - loss: 0.1581 - val_accuracy: 0.6630 - val_loss: 1.1320 - learning_rate: 6.2500e-05
Epoch 41/100
 93/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9533 - loss: 0.1445
Epoch 41: ReduceLROnPlateau reducing learning rate to 3.125000148429535e-05.

Epoch 41: val_loss did not improve from 1.04496
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9559 - loss: 0.1397 - val_accuracy: 0.6630 - val_loss: 1.1324 - learning_rate: 6.2500e-05
Epoch 41: early stopping
Restoring model weights from the end of the best epoch: 26.

In [ ]:
callbacks_cnn = [
    ReduceLROnPlateau(factor=0.4, patience=4, min_lr=0.0000001),
    EarlyStopping(patience=10, restore_best_weights=True),
    ModelCheckpoint('best_cnn.h5', save_best_only=True, monitor='val_accuracy')
]

history_cnn = model_cnn.fit(
    x_train_reshaped, y_train,
    batch_size=64,
    epochs=80,
    validation_data=(x_test_reshaped, y_test),
    class_weight=class_weight_dict,
    callbacks=callbacks_cnn
)

Epoch 1/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.1557 - loss: 2.0554

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

51/51 ━━━━━━━━━━━━━━━━━━━━ 14s 115ms/step - accuracy: 0.1799 - loss: 2.0410 - val_accuracy: 0.1944 - val_loss: 2.0000 - learning_rate: 0.0010
Epoch 2/80
46/51 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2027 - loss: 1.9982

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.2046 - loss: 1.9934 - val_accuracy: 0.2519 - val_loss: 1.9433 - learning_rate: 0.0010
Epoch 3/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.2241 - loss: 1.9729 - val_accuracy: 0.2407 - val_loss: 1.9066 - learning_rate: 0.0010
Epoch 4/80
46/51 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2143 - loss: 1.9762

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.2296 - loss: 1.9626 - val_accuracy: 0.2565 - val_loss: 1.9066 - learning_rate: 0.0010
Epoch 5/80
46/51 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2384 - loss: 1.9207

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2506 - loss: 1.9189 - val_accuracy: 0.2870 - val_loss: 1.8510 - learning_rate: 0.0010
Epoch 6/80
46/51 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2536 - loss: 1.8988

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2651 - loss: 1.8958 - val_accuracy: 0.2917 - val_loss: 1.8176 - learning_rate: 0.0010
Epoch 7/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.2756 - loss: 1.8535 - val_accuracy: 0.2870 - val_loss: 1.8466 - learning_rate: 0.0010
Epoch 8/80
45/51 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2793 - loss: 1.8755

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2898 - loss: 1.8389 - val_accuracy: 0.2963 - val_loss: 1.8032 - learning_rate: 0.0010
Epoch 9/80
46/51 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2929 - loss: 1.8372

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.2988 - loss: 1.8190 - val_accuracy: 0.3046 - val_loss: 1.8094 - learning_rate: 0.0010
Epoch 10/80
46/51 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2720 - loss: 1.8146

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.3062 - loss: 1.7799 - val_accuracy: 0.3491 - val_loss: 1.6802 - learning_rate: 0.0010
Epoch 11/80
47/51 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3416 - loss: 1.7389

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.3383 - loss: 1.7489 - val_accuracy: 0.3593 - val_loss: 1.6542 - learning_rate: 0.0010
Epoch 12/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.3318 - loss: 1.7422 - val_accuracy: 0.3556 - val_loss: 1.6635 - learning_rate: 0.0010
Epoch 13/80
46/51 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3757 - loss: 1.6818

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.3593 - loss: 1.6955 - val_accuracy: 0.4046 - val_loss: 1.6150 - learning_rate: 0.0010
Epoch 14/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.3534 - loss: 1.6760 - val_accuracy: 0.3806 - val_loss: 1.6087 - learning_rate: 0.0010
Epoch 15/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.3478 - loss: 1.6725 - val_accuracy: 0.3833 - val_loss: 1.6009 - learning_rate: 0.0010
Epoch 16/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.3765 - loss: 1.6363 - val_accuracy: 0.3528 - val_loss: 1.6487 - learning_rate: 0.0010
Epoch 17/80
48/51 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.3489 - loss: 1.6423

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.3694 - loss: 1.6050 - val_accuracy: 0.4130 - val_loss: 1.5173 - learning_rate: 0.0010
Epoch 18/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.3812 - loss: 1.6056 - val_accuracy: 0.4037 - val_loss: 1.5370 - learning_rate: 0.0010
Epoch 19/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.3963 - loss: 1.5695 - val_accuracy: 0.4028 - val_loss: 1.5127 - learning_rate: 0.0010
Epoch 20/80
46/51 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3910 - loss: 1.5334

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.3796 - loss: 1.5401 - val_accuracy: 0.4241 - val_loss: 1.4748 - learning_rate: 0.0010
Epoch 21/80
46/51 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4141 - loss: 1.5508

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4049 - loss: 1.5270 - val_accuracy: 0.4259 - val_loss: 1.4805 - learning_rate: 0.0010
Epoch 22/80
46/51 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4180 - loss: 1.5067

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4228 - loss: 1.4974 - val_accuracy: 0.4269 - val_loss: 1.4938 - learning_rate: 0.0010
Epoch 23/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4244 - loss: 1.4802 - val_accuracy: 0.4120 - val_loss: 1.4886 - learning_rate: 0.0010
Epoch 24/80
45/51 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4330 - loss: 1.4629

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4306 - loss: 1.4677 - val_accuracy: 0.4593 - val_loss: 1.4174 - learning_rate: 0.0010
Epoch 25/80
46/51 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4383 - loss: 1.4357

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4265 - loss: 1.4491 - val_accuracy: 0.4722 - val_loss: 1.4304 - learning_rate: 0.0010
Epoch 26/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4469 - loss: 1.4202 - val_accuracy: 0.4324 - val_loss: 1.4270 - learning_rate: 0.0010
Epoch 27/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4503 - loss: 1.3923 - val_accuracy: 0.4574 - val_loss: 1.4288 - learning_rate: 0.0010
Epoch 28/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4500 - loss: 1.4151 - val_accuracy: 0.4602 - val_loss: 1.4254 - learning_rate: 0.0010
Epoch 29/80
46/51 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4783 - loss: 1.3481

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4855 - loss: 1.3201 - val_accuracy: 0.4806 - val_loss: 1.3823 - learning_rate: 4.0000e-04
Epoch 30/80
46/51 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4921 - loss: 1.2862

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4901 - loss: 1.2956 - val_accuracy: 0.4824 - val_loss: 1.3385 - learning_rate: 4.0000e-04
Epoch 31/80
46/51 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5046 - loss: 1.2350

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5000 - loss: 1.2671 - val_accuracy: 0.4861 - val_loss: 1.3534 - learning_rate: 4.0000e-04
Epoch 32/80
46/51 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5067 - loss: 1.2427

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5012 - loss: 1.2616 - val_accuracy: 0.4880 - val_loss: 1.3461 - learning_rate: 4.0000e-04
Epoch 33/80
46/51 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5048 - loss: 1.2505

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5136 - loss: 1.2315 - val_accuracy: 0.4963 - val_loss: 1.3579 - learning_rate: 4.0000e-04
Epoch 34/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5179 - loss: 1.2185 - val_accuracy: 0.4815 - val_loss: 1.3498 - learning_rate: 4.0000e-04
Epoch 35/80
46/51 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5203 - loss: 1.1941

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5284 - loss: 1.1950 - val_accuracy: 0.5102 - val_loss: 1.3181 - learning_rate: 1.6000e-04
Epoch 36/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5346 - loss: 1.1773 - val_accuracy: 0.5074 - val_loss: 1.3153 - learning_rate: 1.6000e-04
Epoch 37/80
46/51 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5494 - loss: 1.1428

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5293 - loss: 1.1714 - val_accuracy: 0.5130 - val_loss: 1.3167 - learning_rate: 1.6000e-04
Epoch 38/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5349 - loss: 1.1701 - val_accuracy: 0.5009 - val_loss: 1.3199 - learning_rate: 1.6000e-04
Epoch 39/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5290 - loss: 1.1797 - val_accuracy: 0.5102 - val_loss: 1.3039 - learning_rate: 1.6000e-04
Epoch 40/80
46/51 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5542 - loss: 1.1320

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5432 - loss: 1.1595 - val_accuracy: 0.5222 - val_loss: 1.2994 - learning_rate: 1.6000e-04
Epoch 41/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5358 - loss: 1.1476 - val_accuracy: 0.5037 - val_loss: 1.3120 - learning_rate: 1.6000e-04
Epoch 42/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.5488 - loss: 1.1308 - val_accuracy: 0.5176 - val_loss: 1.2973 - learning_rate: 1.6000e-04
Epoch 43/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.5481 - loss: 1.1250 - val_accuracy: 0.5167 - val_loss: 1.2960 - learning_rate: 1.6000e-04
Epoch 44/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.5525 - loss: 1.1217 - val_accuracy: 0.5130 - val_loss: 1.2874 - learning_rate: 1.6000e-04
Epoch 45/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.5556 - loss: 1.1154 - val_accuracy: 0.5185 - val_loss: 1.3039 - learning_rate: 1.6000e-04
Epoch 46/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.5596 - loss: 1.1162 - val_accuracy: 0.4963 - val_loss: 1.3061 - learning_rate: 1.6000e-04
Epoch 47/80
48/51 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5465 - loss: 1.1225

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.5586 - loss: 1.1011 - val_accuracy: 0.5250 - val_loss: 1.2875 - learning_rate: 1.6000e-04
Epoch 48/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.5531 - loss: 1.1141 - val_accuracy: 0.5250 - val_loss: 1.2908 - learning_rate: 1.6000e-04
Epoch 49/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5796 - loss: 1.0821 - val_accuracy: 0.5250 - val_loss: 1.2843 - learning_rate: 6.4000e-05
Epoch 50/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5583 - loss: 1.0970 - val_accuracy: 0.5241 - val_loss: 1.2835 - learning_rate: 6.4000e-05
Epoch 51/80
45/51 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5892 - loss: 1.0727

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5781 - loss: 1.0784 - val_accuracy: 0.5259 - val_loss: 1.2755 - learning_rate: 6.4000e-05
Epoch 52/80
46/51 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5546 - loss: 1.1148

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5577 - loss: 1.1028 - val_accuracy: 0.5370 - val_loss: 1.2755 - learning_rate: 6.4000e-05
Epoch 53/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5772 - loss: 1.0764 - val_accuracy: 0.5250 - val_loss: 1.2815 - learning_rate: 6.4000e-05
Epoch 54/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5719 - loss: 1.0876 - val_accuracy: 0.5250 - val_loss: 1.2835 - learning_rate: 6.4000e-05
Epoch 55/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5713 - loss: 1.0809 - val_accuracy: 0.5306 - val_loss: 1.2789 - learning_rate: 6.4000e-05
Epoch 56/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5744 - loss: 1.0725 - val_accuracy: 0.5324 - val_loss: 1.2739 - learning_rate: 2.5600e-05
Epoch 57/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5750 - loss: 1.0794 - val_accuracy: 0.5370 - val_loss: 1.2708 - learning_rate: 2.5600e-05
Epoch 58/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5725 - loss: 1.0751 - val_accuracy: 0.5361 - val_loss: 1.2762 - learning_rate: 2.5600e-05
Epoch 59/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5926 - loss: 1.0562 - val_accuracy: 0.5306 - val_loss: 1.2752 - learning_rate: 2.5600e-05
Epoch 60/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5719 - loss: 1.0718 - val_accuracy: 0.5296 - val_loss: 1.2778 - learning_rate: 2.5600e-05
Epoch 61/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5790 - loss: 1.0699 - val_accuracy: 0.5324 - val_loss: 1.2738 - learning_rate: 2.5600e-05
Epoch 62/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5833 - loss: 1.0673 - val_accuracy: 0.5269 - val_loss: 1.2749 - learning_rate: 1.0240e-05
Epoch 63/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5836 - loss: 1.0494 - val_accuracy: 0.5306 - val_loss: 1.2737 - learning_rate: 1.0240e-05
Epoch 64/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5738 - loss: 1.0728 - val_accuracy: 0.5324 - val_loss: 1.2759 - learning_rate: 1.0240e-05
Epoch 65/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5719 - loss: 1.0689 - val_accuracy: 0.5370 - val_loss: 1.2749 - learning_rate: 1.0240e-05
Epoch 66/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5815 - loss: 1.0580 - val_accuracy: 0.5333 - val_loss: 1.2763 - learning_rate: 4.0960e-06
Epoch 67/80
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5753 - loss: 1.0701 - val_accuracy: 0.5333 - val_loss: 1.2741 - learning_rate: 4.0960e-06

In [ ]:
# Đánh giá hiệu suất của mô hình LSTM trên tập dữ liệu kiểm tra và in ra giá trị của loss và accuracy
loss_lstm, accuracy_lstm = model_lstm.evaluate(x_test_reshaped, y_test)
print("LSTM Model - Loss: {:.4f}, Accuracy: {:.2f}%".format(loss_lstm, accuracy_lstm * 100))

34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5361 - loss: 1.2920
LSTM Model - Loss: 1.2920, Accuracy: 53.61%

In [ ]:
# Đánh giá hiệu suất của mô hình CNN trên tập dữ liệu kiểm tra và in ra giá trị của loss và accuracy
loss_cnn, accuracy_cnn = model_cnn.evaluate(x_test_reshaped, y_test)
print("CNN Model - Loss: {:.4f}, Accuracy: {:.2f}%".format(loss_cnn, accuracy_cnn * 100))

34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.5370 - loss: 1.2708
CNN Model - Loss: 1.2708, Accuracy: 53.70%

In [ ]:
# Chỉnh lại nhãn sau khi dự đoán từ số sang chữ
labels_mapping = {0: 'neutral',1: 'calm', 2: 'happy', 3: 'sad', 4: 'angry', 5: 'fear', 6: 'disgust', 7: 'surprise'}

# Dự đoán nhãn từ chỉ số dự đoán của mô hình LSTM và CNN
y_pred_lstm_labels = [labels_mapping[idx] for idx in y_pred_lstm]
y_pred_cnn_labels = [labels_mapping[idx] for idx in y_pred_cnn]
y_test_labels = [labels_mapping[idx] for idx in y_test_labels]

In [ ]:
# Tạo và in ra báo cáo phân loại, so sánh giữa nhãn thực tế và nhãn dự đoán của mô hình LSTM
print("LSTM Model Classification Report:")
print(classification_report(y_test_labels, y_pred_lstm_labels))

LSTM Model Classification Report:
              precision    recall  f1-score   support

       angry       0.00      0.00      0.00       160
        calm       0.00      0.00      0.00       141
     disgust       0.16      0.91      0.27       143
        fear       0.00      0.00      0.00        76
       happy       0.00      0.00      0.00       142
     neutral       0.33      0.66      0.44       138
         sad       0.00      0.00      0.00       147
    surprise       0.00      0.00      0.00       133

    accuracy                           0.20      1080
   macro avg       0.06      0.20      0.09      1080
weighted avg       0.06      0.20      0.09      1080

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
# Tạo và in ra báo cáo phân loại, so sánh giữa nhãn thực tế và nhãn dự đoán của mô hình CNN
print("CNN Model Classification Report:")
print(classification_report(y_test_labels, y_pred_cnn_labels))

CNN Model Classification Report:
              precision    recall  f1-score   support

       angry       0.00      0.00      0.00       160
        calm       0.00      0.00      0.00       141
     disgust       0.14      0.78      0.23       143
        fear       0.02      0.05      0.03        76
       happy       0.08      0.01      0.01       142
     neutral       0.00      0.00      0.00       138
         sad       0.17      0.03      0.05       147
    surprise       0.00      0.00      0.00       133

    accuracy                           0.11      1080
   macro avg       0.05      0.11      0.04      1080
weighted avg       0.05      0.11      0.04      1080

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
import joblib
from keras.models import load_model

# Load đúng file .keras vừa train
best_lstm = load_model('best_lstm.keras')

# Compile lại để tránh warning
best_lstm.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# Evaluate
loss, acc = best_lstm.evaluate(x_test_reshaped, y_test, verbose=0)
print(f"Best LSTM — Loss: {loss:.4f}, Accuracy: {acc*100:.2f}%")

# Classification report
y_pred = np.argmax(best_lstm.predict(x_test_reshaped), axis=1)
y_true = np.argmax(y_test, axis=1)

labels_mapping = {0:'neutral', 1:'calm', 2:'happy', 3:'sad',
                  4:'angry', 5:'fear', 6:'disgust', 7:'surprise'}

y_pred_labels = [labels_mapping[i] for i in y_pred]
y_true_labels = [labels_mapping[i] for i in y_true]

print("\nBest LSTM Classification Report:")
print(classification_report(y_true_labels, y_pred_labels))

# Save artifacts
best_lstm.save('emotion_recognition_model_LSTM.h5')
joblib.dump(scaler, 'scaler.pkl')
joblib.dump(encoder, 'encoder.pkl')
print("✅ Saved!")

Best LSTM — Loss: 1.0450, Accuracy: 67.22%
34/34 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Best LSTM Classification Report:
              precision    recall  f1-score   support

       angry       0.68      0.63      0.65       160
        calm       0.78      0.70      0.74       141
     disgust       0.58      0.55      0.56       143
        fear       0.47      0.75      0.58        76
       happy       0.69      0.58      0.63       142
     neutral       0.78      0.79      0.79       138
         sad       0.73      0.65      0.69       147
    surprise       0.66      0.78      0.71       133

    accuracy                           0.67      1080
   macro avg       0.67      0.68      0.67      1080
weighted avg       0.68      0.67      0.67      1080

✅ Saved!